//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakalliTicaret.Core.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryPropertyValues
    {
        public int ID { get; set; }
        public int CategoryPropertyId { get; set; }
        public string Value { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public int CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
    
        public virtual CategoryProperties CategoryProperties { get; set; }
    }
}
