//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakalliTicaret.Core.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int ID { get; set; }
        public string Phone { get; set; }
        public string Phone1 { get; set; }
        public string Mail { get; set; }
        public string Mail2 { get; set; }
        public string Adrress { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public int CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public string IframeUrl { get; set; }
    }
}
