//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakalliTicaret.Core.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogCategories
    {
        public int ID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public int CreateUserID { get; set; }
        public string Actions { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
    }
}
