//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakalliTicaret.Core.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogProducts
    {
        public int ID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public int CreateUserID { get; set; }
        public string Actions { get; set; }
        public string Name { get; set; }
        public int CategoryID { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
        public string Definition { get; set; }
        public decimal Price { get; set; }
        public decimal Tax { get; set; }
        public decimal Discount { get; set; }
        public int Stock { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
