//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakalliTicaret.Core.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProducts
    {
        public int ID { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public int CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public int UserId { get; set; }
        public int BasketId { get; set; }
        public bool InTheBasket { get; set; }
        public double Amount { get; set; }
    
        public virtual Baskets Baskets { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
